namespace Auuueser.ScanValue.Core.Configuration;

public static class ConfigTextCatalog
{
    public static ConfigTexts Get(ConfigLanguage language)
    {
        return language == ConfigLanguage.Chinese ? Chinese : English;
    }

    private static readonly ConfigTexts English = new(
        generalSection: "General",
        visibilitySection: "Visibility",
        performanceSection: "Performance",
        labelSection: "Label",
        highlightSection: "Highlight",
        debugSection: "Debug",
        enabledDescription: "Enable automatic scrap value labels. Applied immediately.",
        revealRadiusDescription: "Player-centered reveal radius in meters. Applied immediately.",
        activationModeDescription: "When labels appear: VanillaScan mirrors the vanilla right-click scan UI; Always keeps the old automatic behavior. Old ScanOnly values are treated as VanillaScan. Applied immediately.",
        scanRevealDurationSecondsDescription: "Legacy setting kept for old configs. VanillaScan follows the vanilla scan UI and does not use a timed reveal window. Applied immediately.",
        updateIntervalSecondsDescription: "Seconds between visibility refreshes. Higher values reduce CPU work. Applied immediately.",
        optimizeVanillaScanDescription: "Optimize the vanilla right-click scan by caching scan UI components and avoiding repeated text rebuilds. Applied immediately.",
        maxVisibleLabelsDescription: "Maximum labels shown at once. Applied immediately.",
        heightOffsetDescription: "Vertical world-space offset above each scrap object. Applied immediately.",
        worldScaleDescription: "World-space scale for each label. Applied immediately.",
        fontSizeDescription: "TextMeshPro font size. Applied immediately.",
        labelColorDescription: "HTML color for the price text, for example #FFD447. Applied immediately.",
        outlineColorDescription: "HTML color for the text outline. Applied immediately.",
        outlineWidthDescription: "Text outline width from 0 to 0.5. Applied immediately.",
        highlightEnabledDescription: "Highlight scanned scrap object outlines. Applied immediately.",
        highlightColorDescription: "HTML color for scanned scrap outlines, for example #FFD447. Applied immediately.",
        highlightAlphaDescription: "Opacity for scanned scrap outlines from 0 to 1. Applied immediately.",
        highlightWidthDescription: "World-space outline proxy expansion from 0 to 0.15. Applied immediately.",
        maxHighlightedItemsDescription: "Maximum scanned scrap objects highlighted at once. Applied immediately.",
        showItemNamesDescription: "Show the item name above the scrap value label. Applied immediately.",
        itemNameLanguageDescription: "Item-name language: Auto, Chinese, or English. Applied immediately.",
        valueBasedColorsEnabledDescription: "Color scrap labels and scan outlines by the scanned scrap value. Applied immediately.",
        lowValueMaxDescription: "Maximum value for the low-value color tier. Applied immediately.",
        mediumValueMaxDescription: "Maximum value for the medium-value color tier. Applied immediately.",
        highValueMaxDescription: "Maximum value for the high-value color tier. Applied immediately.",
        veryHighValueMaxDescription: "Maximum value for the very-high-value color tier. Values above this use the jackpot color. Applied immediately.",
        unknownValueColorDescription: "HTML color for unknown scan values such as docked Apparatus ???. Applied immediately.",
        lowValueColorDescription: "HTML color for low-value scrap labels and scan outlines. Applied immediately.",
        mediumValueColorDescription: "HTML color for medium-value scrap labels and scan outlines. Applied immediately.",
        highValueColorDescription: "HTML color for high-value scrap labels and scan outlines. Applied immediately.",
        veryHighValueColorDescription: "HTML color for very-high-value scrap labels and scan outlines. Applied immediately.",
        jackpotValueColorDescription: "HTML color for jackpot-value scrap labels and scan outlines. Applied immediately.",
        debugEnabledDescription: "Enable diagnostic and test-only behavior. Keep disabled for normal play.",
        debugDiagnosticsEnabledDescription: "Debug only: log low-frequency camera, registry, filtering, layout, and pool counters. Requires debug mode. Applied immediately.",
        debugShowHeldItemsDescription: "Show labels for held or pocketed items while debug mode is enabled. Applied immediately.",
        debugShowZeroValueItemsDescription: "Show $0 labels for registered items while debug mode is enabled. Applied immediately.",
        debugLogRegistrationsDescription: "Log item registration events while debug mode is enabled. Applied immediately.",
        debugShowCameraTestLabelDescription: "Debug only: render a fixed $TEST price label in front of the active camera. Requires debug mode. Applied immediately.",
        debugLogIntervalSecondsDescription: "Seconds between debug visibility summaries. Applied immediately.");

    private static readonly ConfigTexts Chinese = new(
        generalSection: "通用",
        visibilitySection: "可见性",
        performanceSection: "性能",
        labelSection: "标签",
        highlightSection: "高光",
        debugSection: "调试",
        enabledDescription: "启用自动废料价格标签。保存后立即生效。",
        revealRadiusDescription: "以本地玩家为中心的显示半径，单位为米。保存后立即生效。",
        activationModeDescription: "标签显示方式：VanillaScan 跟随原版右键 scan UI；Always 保留旧的自动显示行为。旧的 ScanOnly 会按 VanillaScan 处理。保存后立即生效。",
        scanRevealDurationSecondsDescription: "兼容旧配置保留的设置。VanillaScan 跟随原版 scan UI，不再使用计时显示窗口。保存后立即生效。",
        updateIntervalSecondsDescription: "刷新可见性检测的间隔秒数；数值越高，CPU 开销越低。保存后立即生效。",
        optimizeVanillaScanDescription: "优化原版右键 scan：缓存 scan UI 组件并避免重复文本重建。保存后立即生效。",
        maxVisibleLabelsDescription: "同一时间最多显示的价格标签数量。保存后立即生效。",
        heightOffsetDescription: "价格标签相对废料物体向上的世界空间偏移。保存后立即生效。",
        worldScaleDescription: "每个价格标签的世界空间缩放。保存后立即生效。",
        fontSizeDescription: "TextMeshPro 字体大小。保存后立即生效。",
        labelColorDescription: "价格文字的 HTML 颜色，例如 #FFD447。保存后立即生效。",
        outlineColorDescription: "文字描边的 HTML 颜色。保存后立即生效。",
        outlineWidthDescription: "文字描边宽度，范围 0 到 0.5。保存后立即生效。",
        highlightEnabledDescription: "启用 scan 时废料物体轮廓高光。保存后立即生效。",
        highlightColorDescription: "scan 时废料轮廓高光的 HTML 颜色，例如 #FFD447。保存后立即生效。",
        highlightAlphaDescription: "scan 时废料轮廓高光透明度，范围 0 到 1。保存后立即生效。",
        highlightWidthDescription: "scan 时废料轮廓高光代理的外扩宽度，范围 0 到 0.15。保存后立即生效。",
        maxHighlightedItemsDescription: "同一时间最多高光显示的废料数量。保存后立即生效。",
        debugEnabledDescription: "启用诊断和仅测试用行为。正常游玩时保持关闭。",
        debugDiagnosticsEnabledDescription: "仅调试：低频输出相机、注册、过滤、布局和标签池计数日志。需要启用调试模式。保存后立即生效。",
        debugShowHeldItemsDescription: "调试模式开启时，显示被持有或放入口袋的物品价格。保存后立即生效。",
        debugShowZeroValueItemsDescription: "调试模式开启时，为已注册物品显示 $0 标签。保存后立即生效。",
        debugLogRegistrationsDescription: "调试模式开启时，输出物品注册日志。保存后立即生效。",
        debugShowCameraTestLabelDescription: "仅调试：在活动相机前方渲染固定 $TEST 价格标签。需要启用调试模式。保存后立即生效。",
        debugLogIntervalSecondsDescription: "两次调试可见性统计之间的秒数。保存后立即生效。",
        showItemNamesDescription: "在废料价值标签上方显示物品名称。保存后立即生效。",
        itemNameLanguageDescription: "物品名称语言：Auto、Chinese 或 English。保存后立即生效。",
        valueBasedColorsEnabledDescription: "根据扫描到的废料价值为标签文字和轮廓高光变色。保存后立即生效。",
        lowValueMaxDescription: "低价值颜色档的最高价格。保存后立即生效。",
        mediumValueMaxDescription: "中价值颜色档的最高价格。保存后立即生效。",
        highValueMaxDescription: "高价值颜色档的最高价格。保存后立即生效。",
        veryHighValueMaxDescription: "很高价值颜色档的最高价格。超过该值时使用极品颜色。保存后立即生效。",
        unknownValueColorDescription: "未知价值（例如未拔下 Apparatus 的 ???）使用的 HTML 颜色。保存后立即生效。",
        lowValueColorDescription: "低价值废料标签文字和轮廓高光的 HTML 颜色。保存后立即生效。",
        mediumValueColorDescription: "中价值废料标签文字和轮廓高光的 HTML 颜色。保存后立即生效。",
        highValueColorDescription: "高价值废料标签文字和轮廓高光的 HTML 颜色。保存后立即生效。",
        veryHighValueColorDescription: "很高价值废料标签文字和轮廓高光的 HTML 颜色。保存后立即生效。",
        jackpotValueColorDescription: "极品价值废料标签文字和轮廓高光的 HTML 颜色。保存后立即生效。");
}
